# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f2b8bfc8bacd8abfa7a32a2c503b9452a143d9289b7bf913c39c0cf83066415bdaa78ddc9ab37c2cab19d3f2d9d54aade349aa834b39120a84b1727990ce564

test:
  secret_key_base: c3bfd67e4b857fe5dc7439e24ee417de56a272e3f50ba8c5248fdf2e628164ba268523634a0ef98da32a5b7428ff434431581998b01ab94229eff36e6268bc57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
